version: "3"
services:
  crawler:
    build: .
    command: npm run crawl
    env_file:
      - .env.example
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.example
    volumes:
      - pgdata:/var/lib/posgresql/data
  flats:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.example
    command: >
      sh -c "npx prisma migrate dev && npm run start"
    depends_on:
      - db
      - crawler
volumes:
  pgdata:
